### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by UtsavBalar1231** [xiaomi-sm6150/android_device_xiaomi_davinci#1]
https://github.com/xiaomi-sm6150/android_device_xiaomi_davinci/blob/063b3ab108c5b8cdb2100043976178926f55985d/parts/src/org/lineageos/popupcamera/PopupCameraService.java#L313

**Comment by UtsavBalar1231** [comment]
https://del.dog/akignilely.log

**Comment by ArianK16a** [comment]
Thanks for reporting that issue. The coding style here could indeed be improved (i would probably go for a boolean instead of string for ledBreathing), but anyway ledBreathing should never be null here. Do you see anything in the log indicating that FileUtils.readOneLine(Constants.LEFT_LED_BREATH_PATH) fails? (wrong file path or permissions maybe? (note that i have re-labelled the led nodes to left and right instead of blue and green)).

**Comment by UtsavBalar1231** [comment]
No all the nodes are working fine and permissions are same as yours except that I use the default labels for leds. And this crash happens on the first motor up call
The motor popups and retracts after 1s and stays dead

Here is my parts app
https://github.com/UtsavBalar1231/android_device_xiaomi_raphael/commits/android11-release/parts

**Comment by ArianK16a** [comment]
Am i understanding you correctly that this effectively breaks the popup camera for you? I am currently away from my parents home and didn't take davinci with me so i can't test it myself currently. However i'm pretty confident that the camera was working fine after these pushed commits. Have you tried to catch the null pointer exception and checked if it always threw that exception when it tried to open/close or just once?

**Comment by UtsavBalar1231** [comment]
yes it breaks the popup. actually on first call after boot i can call the motor once and it actually retracts back after that NPE and stays retracted and I have not checked that if it always threw that exception. For now i have explicitely set breath=1 on post delayed. And waiting for you to look more into it .

**Comment by ArianK16a** [comment]
Why did yo close this issue? Were you able to fix it?
I won't be able to test anything until the weekend.

**Comment by UtsavBalar1231** [comment]
yeah it was a shameful mistake of mine. And now have been resolved, also hope you still improve that led breathing code.
thanks

**Comment by ArianK16a** [comment]
Oh, okay. Glad to hear that. I will surely revisit this when i get the time for it.
